### ISSUE TITLE
Support running Self-hosted GitHub Actions runners in AWS CodeBuild

### ISSUE THREAD

**Issue by nysdin** [suzuki-shunsuke/go-ci-env#447]
## Feature Overview
I want to make it recognized as a github actions when I run the github runner in codebuild

## Why is the feature needed?
When running a self hosted runner on codebuild, I believe it is currently recognized as the codebuild platform.
When using [ci-info](https://github.com/suzuki-shunsuke/ci-info?tab=readme-ov-file#complement-options-with-platforms-built-in-environment-variables) with the github runner on codebuild, an error occurs because the repo, owner, etc. are not automatically set.
I believe it may be necessary to change the order in which the platform is determined to resolve the error.

## Example Code
related code: https://github.com/suzuki-shunsuke/go-ci-env/blob/main/cienv/platform.go#L43-L56

```go
var platformFuncs = map[string]newPlatform{ //nolint:gochecknoglobals
	"circleci": func(param *Param) Platform {
		return NewCircleCI(param)
	},
        "github-actions": func(param *Param) Platform {
		return NewGitHubActions(param)
	},
	"codebuild": func(param *Param) Platform {
		return NewCodeBuild(param)
	},
	"drone": func(param *Param) Platform {
		return NewDrone(param)
	},
}
```

## Note

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
Unfortunately, I don't have the environment of Self-hosted GitHub Actions runners on AWS CodeBuild.
So I'm not sure which environment variables are set.

**Comment by suzuki-shunsuke** [comment]
> When using [ci-info](https://github.com/suzuki-shunsuke/ci-info?tab=readme-ov-file#complement-options-with-platforms-built-in-environment-variables) with the github runner on codebuild, an error occurs because the repo, owner, etc. are not automatically set.

As a workaround, you can pass those parameters by command line options.
I'm aware this isn't ideal.

**Comment by rakiyoshi** [comment]
Thanks! It worked as I expected on CodeBuild-hosted runner!
I'm looking forward to this version being available in `github-comment` and `tfaction`.

Workflow file:

```yaml
name: test
on: 
  pull_request:
permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on:
      - codebuild-github-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.54.1
      - run: |
          ci-info --version
          for i in `seq 1 50`; do
            echo ====
            ci-info run
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Output:

```
...(Logs from aqua)
ci-info version 2.4.0 (f90c96172b4fec6187175f7ab4b132ef12445d00)
====
export CI_INFO_IS_PR=true
export CI_INFO_HAS_ASSOCIATED_PR=true
export CI_INFO_PR_NUMBER=3
export CI_INFO_BASE_REF=main
export CI_INFO_HEAD_REF=chore/test-ci-info
export CI_INFO_PR_AUTHOR=rakiyoshi
export CI_INFO_PR_MERGED=false
export CI_INFO_TEMP_DIR=/tmp/ci-info283246342
export CI_INFO_REPO_OWNER=rakiyoshi
export CI_INFO_REPO_NAME=codebuild-gha-test
====
...(same logs 49 times)
```
