### ISSUE TITLE
Request for support getting pull request number in case of merge_group event

### ISSUE THREAD

**Issue by ishii1648** [suzuki-shunsuke/go-ci-env#81]
### Feature Overview
Request for support getting pull request number in case of merge_group event.

### Why is the feature needed?
Currently, I'm thinking to use `tfaction/apply` in case of merge_group event. 

As demonstrated in [this sample](https://github.com/suzuki-shunsuke/tfaction-example/blob/main/.github/workflows/apply.yaml), I think that it is recommended to use `tfaction/setup` before tfaction/apply.

The pull request information to execute terraform apply is obtained from [here](https://github.com/suzuki-shunsuke/tfaction/blob/v1.5.1/setup/action.yaml#L26-L31) in tfaction/setup, and the pull request number is obtained [here](https://github.com/suzuki-shunsuke/go-ci-env/blob/v3.0.1/cienv/github_actions.go#L83-L98) in `go-ci-env`. I think the current implementation doesn't get pull request number in case of merge_group event becase there is no exist pull request number in `GITHUB_EVENT_PATH`.

I want go-ci-env to support getting pull request number in case of merge_group event.

#### workflows/test.yml
```yaml
name: run ci-info pull_request and merge_group

on:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.29.0
      - run: ci-info run
        env:
          GITHUB_TOKEN: ${{ secrets.HOGE }}
```

#### github actions log
pull_request event
```console
...
export CI_INFO_IS_PR=true
export CI_INFO_HAS_ASSOCIATED_PR=true
export CI_INFO_PR_NUMBER=163
export CI_INFO_BASE_REF=main
export CI_INFO_HEAD_REF=tfaction-test2
export CI_INFO_PR_AUTHOR=hogehoge
export CI_INFO_PR_MERGED=false
export CI_INFO_TEMP_DIR=/tmp/ci-info194576901
export CI_INFO_REPO_OWNER=hoge
export CI_INFO_REPO_NAME=hogehoge
```

merge_group event
```console
...
export CI_INFO_HAS_ASSOCIATED_PR=false
export CI_INFO_IS_PR=false
export CI_INFO_REPO_OWNER=hoge
export CI_INFO_REPO_NAME=hogehoge
```

### Proposal

I think the following implementation can obtain the pull request number in case of merge_group event (but no tested).

#### cienv/github_actions.go
```go
type gitHubActionsPayload struct {
	Action string `json:"action"`
	PullRequest struct {
		Number int `json:"number"`
	} `json:"pull_request"`
	MergeGroup struct {
		HeadSha string `json:"head_sha"`
	}
}

func (gha *GitHubActions) getPRNumberFromPayload(body io.Reader) (int, error) {
	p := gitHubActionsPayload{}
	if err := json.NewDecoder(body).Decode(&p); err != nil {
		return 0, fmt.Errorf("parse a GitHub Action payload: %w", err)
	}
	if p.Action == "checks_requested" {
		// head_ref: refs/heads/gh-readonly-queue/<head_branch>/pr-<pull_request_number>-<commit_sha>
		mergeGroupHeadShaLastStr := strings.Split(p.MergeGroup.HeadSha, "/")[4]
		prNumber, _ := strconv.Atoi(strings.Split(mergeGroupHeadShaLastStr, "-")[1])
		return prNumber, nil
	}
	return p.PullRequest.Number, nil
}
```
